services:
  - type: web
    name: medieval-explorer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        sync: false
